config/routes.rb
Rails.application.routes.draw do
root to:  "alimentar_carro#index"
  get 'alimentar_carro/index'
  get 'alimentar_carro/import' => 'carros#my_import'
  get 'users/new'
  get 'admin/import'
 devise_for :users
 resources :carros do
 collection {post :import}
 end
 





  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
end

app/models/alimentar_carro.rb
class AlimentarCarro < ApplicationRecord
require 'csv'
require 'activerecord-import/base'

def self.my_import(file)
	carros=[]
	CSV.foreach(file.path, headers: true) do |row|
		carros << Carro.new(row.to_h)
	end
		Carro.import carros, recursive: true
	end
end

app/models/aluguel.rb
class Aluguel < ApplicationRecord
has_one :carro
has_one :cliente
has_one  :sinistro
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carro.rb
class Carro < ApplicationRecord
has_one :aluguel

    # Bulk upload companies
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            company_hash = Carro.new
            company_hash.marca = row[0]
            company_hash.tipo = row[1]
			company_hash.disponivel = row[2]
			company_hash.created_at = row[3]
			company_hash.updated_at = row[4]
			 
            company_hash.save
        end
    end
end

app/models/cliente.rb
class Cliente < ApplicationRecord
has_one :aluguel
end

app/models/sinistro.rb
class Sinistro < ApplicationRecord
has_one:aluguel
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/alimentar_carro_controller.rb
class AlimentarCarroController < ApplicationController
  def index
  @carros = Carro.all
  end

  def import
   Carro.my_import(params[:file])
   redirect_to root_url, notice: "Importação feita com sucesso!"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


	
    
	


end

app/controllers/import_controller.rb
class ImportController < ApplicationController


end

app/controllers/items_imports_controller.rb
class ItemsImportsController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/alimentar_carro_helper.rb
module AlimentarCarroHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/items_imports_helper.rb
module ItemsImportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/import.html.erb
< p  class = " active_admin_import_hint " >
   <% = raw ( @active_admin_import_model .hint) %> 
</ p >
<% = semantic_form_for @active_admin_import_model , url: { ação  :: do_import }, html: { multipart:  true } do | f | %>
    <% = f.inputs name: t ( " active_admin_import.details " ) do  %>
        <% = f.input : file , como  :: arquivo  %>
    <% end %>  
    <% = f.actions do  %>
        <% = f.action : submit , label: t ( " active_admin_import.import_btn " ), button_html: { dados: { disable_with: t ( " active_admin_import.import_btn_disabled " )}} %>
    <% end %>  
<% end %>  

app/views/alimentar_carro/import.html.erb
<h1>AlimentarCarro#import</h1>
<p>Find me in app/views/alimentar_carro/import.html.erb</p>

app/views/alimentar_carro/index.html.erb
<%= flash[:notice]%>
<div>
<h4>Importar dados de para carros</h4>
	<%= form_tag import_carros_path, multipart: true do%>
		<%= file_field_tag :file%>
		<%= submit_tag "Import from file"%>
	<% end%>
</div>

<table>
	<thead>
		<tr>
		 <th>Marca </th>
		 <th>Tipo </th>
		 <th>Disponivel </th>
		 <th>Criado em </th>
		 <th>Atualizado em</th>
		 </tr>
	</thead>
	<tbody>
		<% @carros.each do |carro| %>
			<tr>
			<td><%= carro.marca%></td>
			<td><%= carro.tipo%></td>
			<td><%= carro.disponivel%></td>
			<td><%= carro.created_at%></td>
			<td><%= carro.updated_at%></td>
			</tr>
		<% end %>
	</tbody>
</table>

			

app/views/items_imports/create.html.erb
<h1>ItemsImports#create</h1>
<p>Find me in app/views/items_imports/create.html.erb</p>

app/views/items_imports/new.html.erb
<h1>ItemsImports#new</h1>
<p>Find me in app/views/items_imports/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>
 
    <title>Rentcar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
	

  </body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>